"""Convert RunResult list to an ATLAS Navigator layer JSON."""

from __future__ import annotations

import json
from typing import Any

from ..runner import RunResult

_TECHNIQUE_ID_RE = __import__("re").compile(r"AML\.(T[0-9]+(?:\.[0-9]+)?)")


def to_navigator_layer(results: list[RunResult], name: str = "atomic-atlas coverage") -> dict[str, Any]:
    """Build an ATLAS Navigator layer from a list of RunResults."""
    techniques = []
    for r in results:
        m = _TECHNIQUE_ID_RE.search(r.atlas_technique)
        technique_id = m.group(1) if m else r.atlas_technique

        score = r.success_rate
        color = _score_to_color(score)
        comment = (
            f"Vector: {r.interaction_vector} | "
            f"{r.successes}/{r.total_runs} runs succeeded ({score:.0%})"
        )
        techniques.append({
            "techniqueID": technique_id,
            "tactic": None,
            "color": color,
            "comment": comment,
            "enabled": True,
            "metadata": [
                {"name": "vector", "value": r.interaction_vector},
                {"name": "success_rate", "value": f"{score:.2f}"},
                {"name": "guid", "value": r.guid},
            ],
            "showSubtechniques": False,
        })

    return {
        "name": name,
        "versions": {"attack": "14", "navigator": "4.9", "layer": "4.5"},
        "domain": "mitre-atlas",
        "description": "Generated by atomic-atlas",
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", "#ff4500"],
            "minValue": 0,
            "maxValue": 1,
        },
        "legendItems": [
            {"label": "No success (0%)", "color": "#ffffff"},
            {"label": "Partial success", "color": "#ff9966"},
            {"label": "Full success (100%)", "color": "#ff4500"},
        ],
    }


def _score_to_color(rate: float) -> str:
    if rate == 0:
        return "#f0f0f0"
    r = int(255)
    g = int(255 * (1 - rate) * 0.6)
    b = int(255 * (1 - rate) * 0.6)
    return f"#{r:02x}{g:02x}{b:02x}"
