"""Convert RunResult list to an ATLAS Navigator layer JSON."""

from __future__ import annotations

import json
from typing import Any

from ..runner import RunResult

_TECHNIQUE_ID_RE = __import__("re").compile(r"AML\.(T[0-9]+(?:\.[0-9]+)?)")


def to_navigator_layer(results: list[RunResult], name: str = "atomic-atlas coverage") -> dict[str, Any]:
    """Build an ATLAS Navigator layer from a list of RunResults."""
    techniques = []
    for r in results:
        m = _TECHNIQUE_ID_RE.search(r.atlas_technique)
        technique_id = m.group(1) if m else r.atlas_technique

        score = r.success_rate
        color = _score_to_color(score)
        comment = (
            f"Vector: {r.interaction_vector} | "
            f"{r.successes}/{r.total_runs} runs succeeded ({score:.0%})"
        )
        evidence_count, top_extracted = _summarize_evidence(r.run_details)
        metadata = [
            {"name": "vector", "value": r.interaction_vector},
            {"name": "success_rate", "value": f"{score:.2f}"},
            {"name": "guid", "value": r.guid},
            {"name": "evidence_count", "value": str(evidence_count)},
        ]
        if top_extracted:
            metadata.append({"name": "top_extracted", "value": top_extracted})
        techniques.append({
            "techniqueID": technique_id,
            "tactic": None,
            "color": color,
            "comment": comment,
            "enabled": True,
            "metadata": metadata,
            "showSubtechniques": False,
        })

    return {
        "name": name,
        "versions": {"attack": "14", "navigator": "4.9", "layer": "4.5"},
        "domain": "mitre-atlas",
        "description": "Generated by atomic-atlas",
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", "#ff4500"],
            "minValue": 0,
            "maxValue": 1,
        },
        "legendItems": [
            {"label": "No success (0%)", "color": "#ffffff"},
            {"label": "Partial success", "color": "#ff9966"},
            {"label": "Full success (100%)", "color": "#ff4500"},
        ],
    }


def _summarize_evidence(run_details: list[dict[str, Any]]) -> tuple[int, str]:
    """Count evidence dicts and pick the most-cited extracted value across runs.

    Returns ``(evidence_count, top_extracted)`` where ``top_extracted`` is a
    short string like ``openai_key=sk-test-abc123 (3x)`` or ``""`` if nothing
    was extracted across the runs.
    """
    count = 0
    extracted_freq: dict[tuple[str, str], int] = {}
    for d in run_details or []:
        ev = d.get("evidence")
        if not ev:
            continue
        count += 1
        for name, hits in (ev.get("extracted") or {}).items():
            for h in hits:
                key = (name, h)
                extracted_freq[key] = extracted_freq.get(key, 0) + 1
    if not extracted_freq:
        return count, ""
    (name, value), n = max(extracted_freq.items(), key=lambda kv: kv[1])
    return count, f"{name}={value} ({n}x)"


def _score_to_color(rate: float) -> str:
    if rate == 0:
        return "#f0f0f0"
    r = int(255)
    g = int(255 * (1 - rate) * 0.6)
    b = int(255 * (1 - rate) * 0.6)
    return f"#{r:02x}{g:02x}{b:02x}"
